name: Eclipse-Dash IP-Check

on:
  push:
    branches: [ "main" , "dashIPCheck/requestIpLab"]
  pull_request:
    branches: [ "main" , "dashIPCheck/requestIpLab"]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@5896cecc08fd8a1fbdfaf517e29b571164b031f7 # v4.2.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        EXCLUDED_ARTIFACTS: 'bugsnag'
        DASH_IPLAB_TOKEN: ${{ secrets.DASH_IPLAB_TOKEN }}
      run: mvn -B org.eclipse.dash:license-tool-plugin:license-check -Dlicenses-check -Ddash.fail=true -Ddash.summary=DEPENDENCIES -DexcludeArtifactIds=$EXCLUDED_ARTIFACTS -Ddash.projectId=technology.daanse -Ddash.iplab.token="$DASH_IPLAB_TOKEN" -P eclipse-licenses-check --file pom.xml
