name: Editor Config format check

on:
  pull_request:
    branches: [ "main" , "dashIPCheck/requestIpLab"]

permissions:
  contents: read

jobs:
  validate:
    name: Validate Editor Config formatting
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout PR head branch
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      with:
        fetch-depth: 0
    - name: Editor Config Validation against PR base commit
      uses: github/super-linter/slim@2bf52ff3efef9acb8d56f1840e72984339f0d2a8 # v5.2.1
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_EDITORCONFIG: true
        DEFAULT_BRANCH: ${{ github.event.pull_request.base.sha }}
