name: JavaDoc Check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #Build with java 21
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 #v4.0.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -Pjavadoc-check -B package --file pom.xml
